### ISSUE TITLE
Captcha spinning indefinitely

### ISSUE THREAD

**Issue by YutoDevFR** [Nika0000/cloudflare_turnstile#12]
Hello,

I'm encountering issues with the latest version. Version 2.0.3 was working fine for me, but after updating to version 3.1.1, it no longer functions as expected.

The Captcha gets stuck at this stage:
![image](https://github.com/user-attachments/assets/46666eee-266b-4ef7-8046-f2c5d081b38c)
Then, after a while, I see this:
![image](https://github.com/user-attachments/assets/6b8771e5-965d-48eb-9b54-41ac6bea9d75)

Also, there are no logs in my console or Sentry, which makes it difficult to troubleshoot.

Thank for your help !

**Comment by YutoDevFR** [comment]
edit: i have this log: Unable to load asset: "packages/flutter_turnstile/data/trunstile.html". The asset does not exist or has empty data.

**Comment by Nika0000** [comment]
> edit: i have this log: Unable to load asset: "packages/flutter_turnstile/data/trunstile.html". The asset does not exist or has empty data.

It looks like it might be comming from a different package, possibily one named `flutter_turnstile`. The [cloudflare_turnstile](https://pub.dev/packages/cloudflare_turnstile) package itself doesn't load assets from your project`s assets bundle.

**Comment by Nika0000** [comment]
> Hello,
> 
> I'm encountering issues with the latest version. Version 2.0.3 was working fine for me, but after updating to version 3.1.1, it no longer functions as expected.
> 
> The Captcha gets stuck at this stage:
> ![image](https://github.com/user-attachments/assets/46666eee-266b-4ef7-8046-f2c5d081b38c)
> Then, after a while, I see this:
> ![image](https://github.com/user-attachments/assets/6b8771e5-965d-48eb-9b54-41ac6bea9d75)
> 
> Also, there are no logs in my console or Sentry, which makes it difficult to troubleshoot.
> 
> Thank for your help !

Turnstile is stuck today, this issue is not related to the cloudflare_turnstile package.

**Comment by Nika0000** [comment]
@YutoDevFR `cloudflare_turnstile: 3.1.1` is retracted, use the [latest version](https://pub.dev/packages/cloudflare_turnstile/admin).
