### ISSUE TITLE
iOS not able to render captcha - 3.0.1/3.1.1

### ISSUE THREAD

**Issue by denys-rebikov** [Nika0000/cloudflare_turnstile#13]
Hello. We have an issue that is specific for iOS, captcha for Android is working as expected.

For 3.0.1 we get an invalid domain error for muliple frames and after that captcha dissapears.
For 3.1.1 widget is not visible at all.
There are no errors, nor any logs or warnings in console. 

We are using default Flutter 3.24.3
Our setup for captcha is:
```
CloudflareTurnstile(
  siteKey: _siteKey,
  baseUrl: Application.instance.webSiteHost,
  onTokenExpired: onError,
  onTokenReceived: onSuccess,
  onError: (_) => onError?.call(),
  options: TurnstileOptions(
    language: Application.instance.languageCode,
    retryAutomatically: false,
    size: TurnstileSize.normal,
    theme: TurnstileTheme.light,
  ),
),
```

Downgrading to 2.0.3 is not an option since we encountering another older issue with it.

**Comment by Nika0000** [comment]
If you see something like this, first check if the baseUrl is correct.
[this](https://community.cloudflare.com/t/im-trying-to-add-turnstyle-but-it-keeps-saying-invalid-domain/675511/2)
<img width="314" alt="capture" src="https://github.com/user-attachments/assets/ae866688-1013-4322-8df3-f6fd6e7bac36">

**Comment by Nika0000** [comment]
If you see something like this then first check if the `baseUrl` is correct or not.
Also if you use the turnstile widget on multiple websites, refer to this [issue](https://community.cloudflare.com/t/im-trying-to-add-turnstyle-but-it-keeps-saying-invalid-domain/675511/2).

<img width="314" alt="capture" src="https://github.com/user-attachments/assets/3ac767b3-f0f6-4dc5-b660-3eb5fdfe13df">

**Comment by Nika0000** [comment]
`cloudflare_turnstile: 3.1.1` is retracted, use the [latest version](https://pub.dev/packages/cloudflare_turnstile/admin).

**Comment by denys-rebikov** [comment]
Thank you. Tried on 3.1.2

Logs were helpful on this version, it's appeared that we are getting 110200. Will doublecheck our cloudflare settings tomorrow to verify links & keys. Also will check for mentioned multiple websites issue, that could be our case.

By the way iOS turnstile now renders well, but Android captcha is not rendered in this particular case. So it is like vice versa situation now compared  to 3.1.1👀

**Comment by denys-rebikov** [comment]
Hello. 
Thanks for hinting us cloudflare issue, we were able to fix our links.

Though, there is still an issue for 3.1.2.
If we get captcha fetch error(for expamle from cloudflare) on Android, widget will not be rendered.

I will specify affected Android versions a bit later.

**Comment by Nika0000** [comment]
> Hello. Thanks for hinting us cloudflare issue, we were able to fix our links.
> 
> Though, there is still an issue for 3.1.2. If we get captcha fetch error(for expamle from cloudflare) on Android, widget will not be rendered.
> 
> I will specify affected Android versions a bit later. I also can close this issue and create a new one, if it will be more handy.

Hi, 
If a problem occurs during CAPTCHA challange, the widget will be rendered only if the error is retriable.

You can check if the error is retryable:
```dart
CloudflareTurnstile(
  siteKey: '3x00000000000000000000FF',
  onError: (error) {
      if(error.retryable) {
          // widget will be visible
      }
  }
),
```

**Comment by Nika0000** [comment]
I'm closing this issue, if something similar happens again, you can reopen it or create a new one.
