### ISSUE TITLE
The method 'CloudflareTurnstile' isn't defined for the type '_SignupPageState

### ISSUE THREAD

**Issue by Suezp226** [Nika0000/cloudflare_turnstile#14]
i was add this package like the readme but my code show that
The method 'CloudflareTurnstile' isn't defined for the type '_SignupPageState

**Comment by Nika0000** [comment]
Can you describe your problem in more detail so I can help you?

- Widget mode (invisible/interactive)
- `cloudflare_turnstile` package version
- How to add a widget to the widget tree
- On which platform the issue occurred

**Comment by Suezp226** [comment]
![WX20241105-011121@2x](https://github.com/user-attachments/assets/746bd6db-ffee-4740-a4a4-bbc60bc0cd4a)
i add the code like example but my andriod studio shown this. thank you

**Comment by Suezp226** [comment]
> Can you describe your problem in more detail so I can help you?
> 
> * Widget mode (invisible/interactive)
> * `cloudflare_turnstile` package version
> * On which platform the issue occurred



> Can you describe your problem in more detail so I can help you?
> 
> * Widget mode (invisible/interactive)
> * `cloudflare_turnstile` package version
> * On which platform the issue occurred

cloudflare_turntile version is 2.0.3,and i want use in ios & andriod, but when i add the code from "example", it shown "The method 'CloudflareTurnstile' isn't defined"

![WX20241105-011121@2x](https://github.com/user-attachments/assets/56e38685-4e13-490e-978a-677cc13053e0)

**Comment by Suezp226** [comment]
> Can you describe your problem in more detail so I can help you?
> 
> * Widget mode (invisible/interactive)
> * `cloudflare_turnstile` package version
> * On which platform the issue occurred

cloudflare_turntile version is 2.0.3,and i want use in ios & andriod, but when i add the code from "example", it shown "The method 'CloudflareTurnstile' isn't defined"
![WX20241105-011528@2x](https://github.com/user-attachments/assets/ab78f27d-c9b7-4fb6-8767-3b63b234f0b9)

**Comment by Nika0000** [comment]
@Suezp226 It sounds like there might be an issue with the package import or setup. When you see “The method 'CloudflareTurnstile' isn't defined,” it’s usually because either the package hasn’t been imported correctly or there's a typo.

- Check your import: Make sure you’ve added the import statement at the top of your Dart file:
```dart
import 'package:cloudflare_turnstile/cloudflare_turnstile.dart';
```
- Double-check that you’re using the latest version in `pubspec.yaml`. Sometimes, running `flutter pub get` after updating `pubspec.yaml` helps.

Also version 2.x no longer maintenance. Please use the latest version.

**Comment by Suezp226** [comment]
> @Suezp226 It sounds like there might be an issue with the package import or setup. When you see “The method 'CloudflareTurnstile' isn't defined,” it’s usually because either the package hasn’t been imported correctly or there's a typo.
> 
> * Check your import: Make sure you’ve added the import statement at the top of your Dart file:
> 
> ```dart
> import 'package:cloudflare_turnstile/cloudflare_turnstile.dart';
> ```
> 
> * Double-check that you’re using the latest version in `pubspec.yaml`. Sometimes, running `flutter pub get` after updating `pubspec.yaml` helps.
> 
> Also version 2.x no longer maintenance. Please use the latest version.

thank you do much， i fund that my dart version is no support this component version 3.x， so flutter auto install 2.x， and i upgrade width “flutter upgrade” and add version 3.x it work nice.
