### ISSUE TITLE
Unable to use turnstile invisible and visible widget

### ISSUE THREAD

**Issue by hanumanjiblog** [Nika0000/cloudflare_turnstile#15]
I/chromium( 7956): [INFO:CONSOLE(0)] "The resource https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/cmg/1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)

[INFO:CONSOLE(1)] "Uncaught TypeError: window.flutter_inappwebview.callHandler is not a function", source: https://challenges.cloudflare.com/turnstile/v0/b/22755d9a86c9/api.js (1)

[INFO:CONSOLE(1)] "Unrecognized feature: 'cross-origin-isolated'.", source: https://challenges.cloudflare.com/turnstile/v0/b/22755d9a86c9/api.js (1)

**Comment by Nika0000** [comment]
Hi @hanumanjiblog, can you help me understand the issue a bit better? Just need to clarify a few things:
- Does this problem happen only on Android?
- Which version of the `cloudflare_turnstile` package are you using?
- Have you tried the [test keys](https://developers.cloudflare.com/turnstile/troubleshooting/testing/#dummy-sitekeys-and-secret-keys)?

**Comment by hanumanjiblog** [comment]
Does this problem happen only on Android?
yes
Which version of the cloudflare_turnstile package are you using?
3.1.2 / 3.2.0 both
Have you tried the test keys?
yes

Yes I got same problem after update also

**Comment by Nika0000** [comment]
Are you using `flutter_inappwebview` or `webview_flutter` packages?
also try
```sh
flutter clean & flutter pub get
```

**Comment by kingrupam** [comment]
yes I am using flutter_inappwebview or webview_flutter both in my app

**Comment by hanumanjiblog** [comment]
yes I am using flutter_inappwebview or webview_flutter both in my app
