### ISSUE TITLE
Flutter web wasm UnimplementedError: Cannot call this method on the facade implementation of CloudflareTurnstile

### ISSUE THREAD

**Issue by skiunke** [Nika0000/cloudflare_turnstile#16]
**Describe the bug**
Turnstyle works normally, but not for a changed target of WASM for flutter web running on 3.24.4.

**To Reproduce**
1. Create a sample project
2. Add the turnstile package
3. Creat a widget with the turnstyle
4. flutter run -d chrome --wasm
5. the turnstile is just a big grey box

**Expected behavior**
Turnstyle box shows correctly

**Screenshots**
![image](https://github.com/user-attachments/assets/b6419069-a9ef-443b-8318-a27df627489f)

**Environment (please complete the following information):**
 Flutter (Channel stable, 3.24.4, on Debian GNU/Linux 12 (bookworm) 6.1.0-27-amd64, locale en_US.UTF-8)
**Additional context**
This is probably related to the https://github.com/Nika0000/cloudflare_turnstile/blob/legacy/lib/src/controller/impl/turnstile_controller_web.dart import of `import 'dart:js' as js;` as this is not longer supported for WASM. See https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm

**Comment by Nika0000** [comment]
Hi,

Right now, the `cloudflare_turnstile` package doesn't support WebAssembly (WASM) compilation for Flutter web, which is likely the issue you're seeing. But don't worry - im working on adding WASM support, and the feature should be rolling out next week.

**Comment by skiunke** [comment]
> Hi,
> 
> Right now, the `cloudflare_turnstile` package doesn't support WebAssembly (WASM) compilation for Flutter web, which is likely the issue you're seeing. But don't worry - im working on adding WASM support, and the feature should be rolling out next week.

NIce to hear that it's already getting implemented. Thanks!

**Comment by skiunke** [comment]
@Nika0000 thank's for working on it, can you give a schedule about the upcoming patch? Would love to use it in the wasm version for the production version

**Comment by Nika0000** [comment]
> @Nika0000 thank's for working on it, can you give a schedule about the upcoming patch? Would love to use it in the wasm version for the production version

I'm tied up with other things at the moment, but I’ll try to have the patch schedule ready for you by next week. Thanks for your understanding.

**Comment by Nika0000** [comment]
Hi @skiunke,

You can try out the beta version:

```yaml
dependencies:
  cloudflare_turnstile: ^3.3.0-beta
```
If you encounter any issues, feel free to reopen this issue. Thanks!

**Comment by skiunke** [comment]
@Nika0000 I'm using the 3.3.0-beta version; however, I get the following exception. 

```
Uncaught TurnstileError: [Cloudflare Turnstile] Invalid type for "container", expected "selector" or an implementation of "HTMLElement", got "#cf-turnstile".
    at m (api.js?onload=onloadTurnstileCallback:1:10491)
    at Object.S [as render] (api.js?onload=onloadTurnstileCallback:1:26181)
    at window.onloadTurnstileCallback (<anonymous>:2:34)
    at api.js?onload=onloadTurnstileCallback:1:46604
```

**Comment by andersan** [comment]
Also seeing a very similar error to skiunke above, which happens intermittently: `Uncaught TurnstileError: [Cloudflare Turnstile] Invalid type for "container", expected "selector" or an implementation of "HTMLElement", got ".cf-turnstile__turnstile__1768585929478000".`

Running the latest v3.6.2, using CanvasKit renderer. Happened for both a Linux and Mac user on Chrome.

I don't think this error is related to the use of `wasm`.
