### ISSUE TITLE
When the project cloudflare_turnstile is used together with webview_flutter, cloudflare_turnstile will fail to load.

### ISSUE THREAD

**Issue by PeaMiMi** [Nika0000/cloudflare_turnstile#2]
When I use cloudflare_turnstile in the project, the loading will fail. After troubleshooting and deleting the webview_flutter dependency, cloudflare_turnstile can load normally.

D/InAppWebView( 1335): Using InAppWebViewClientCompat implementation
W/cr_WebSettings( 1335): setForceDark() is a no-op in an app with targetSdkVersion>=T
W/cr_SupportWebSettings( 1335): setForceDarkBehavior() is a no-op in an app with targetSdkVersion>=T
E/MethodChannel#flutter/platform_views( 1335): Failed to handle method call
E/MethodChannel#flutter/platform_views( 1335): java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/MethodChannel#flutter/platform_views( 1335):  at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/MethodChannel#flutter/platform_views( 1335):  at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/MethodChannel#flutter/platform_views( 1335):  at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/MethodChannel#flutter/platform_views( 1335):  at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/MethodChannel#flutter/platform_views( 1335):  at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/MethodChannel#flutter/platform_views( 1335):  at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views( 1335):  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 1335):  at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#flutter/platform_views( 1335):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 1335):  at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views( 1335):  at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views( 1335):  at android.app.ActivityThread.main(ActivityThread.java:7884)
E/MethodChannel#flutter/platform_views( 1335):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 1335):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views( 1335):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 1335): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter ( 1335):      at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter ( 1335):      at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter ( 1335):      at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter ( 1335):      at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter ( 1335):      at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter ( 1335):      at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter ( 1335):      at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/flutter ( 1335):      at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/flutter ( 1335):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter ( 1335):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 1335):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 1335):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 1335):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 1335):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 1335):      at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 1335):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 1335):      at android.os.Looper.loopOnce(Looper.java:201)
E/flutter ( 1335):      at android.os.Looper.loop(Looper.java:288)
E/flutter ( 1335):      at android.app.ActivityThread.main(ActivityThread.java:7884)
E/flutter ( 1335):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 1335):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 1335):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 1335): )
E/flutter ( 1335): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 1335): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 1335): <asynchronous suspension>
E/flutter ( 1335): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099:5)
E/flutter ( 1335): <asynchronous suspension>
E/flutter ( 1335): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822:5)
E/flutter ( 1335): <asynchronous suspension>
E/flutter ( 1335):

**Comment by Nika0000** [comment]
I fixed it for the next realease. 

Before that:

```sh
flutter pub remove cloudflare_turnstile
```

Modify `pubspec.yaml`
```yaml
dependency_overrides: 
  cloudflare_turnstile:
    git:
      url: https://github.com/Nika0000/cloudflare_turnstile.git
      ref: feature/webview_flutter
```
