### ISSUE TITLE
Cloudflare_turnstile works fine on android but not on ios

### ISSUE THREAD

**Issue by QuangTom** [Nika0000/cloudflare_turnstile#3]
I have configured android and ios the same. But the Android side displays normally while the iOS side doesn't display anything.
No console log.

Cloudflare_turnstile version 1.2.3

Here's source code:

import 'package:cloudflare_turnstile/cloudflare_turnstile.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import '../../../../../core/functions/trans.dart';
import '../../../../../core/resources/config/api.dart';
import '../../../../../core/resources/strings.dart';

class CloudflareCaptchaWidget extends StatefulWidget {
  final Function? onChanged;
  const CloudflareCaptchaWidget({Key? key, this.onChanged}) : super(key: key);

  @override
  State<CloudflareCaptchaWidget> createState() =>
      _CloudflareCaptchaWidgetState();
}

class _CloudflareCaptchaWidgetState extends State<CloudflareCaptchaWidget> {
  final TurnstileController _controller = TurnstileController();
  final TurnstileOptions _options = TurnstileOptions(
    mode: TurnstileMode.auto,
    size: TurnstileSize.normal,
    theme: TurnstileTheme.light,
    refreshExpired: TurnstileRefreshExpired.manual,
    language: trans(LANGUAGE_VI),
    retryAutomatically: false,
  );
  String? _token;

  @override
  void setState(fn) {
    if (mounted) {
      super.setState(fn);
    }
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: [
          CloudFlareTurnstile(
            siteKey: SITE_KEY_CLOUDFLARE,
            baseUrl: cloudflareUrl,
            options: _options,
            controller: _controller,
            onTokenRecived: (token) {
              setState(() {
                _token = token;
              });
              _controller.isExpired().then((isExpired) {
                if (!isExpired && widget.onChanged != null) {
                  widget.onChanged!(!isExpired);
                }
              });
            },
            onTokenExpired: () {},
            onError: (error) {
              if (kDebugMode) {
                print('Captcha error: $error');
              }
            },
          ),
        ],
      ),
    );
  }
}

**Comment by QuangTom** [comment]
Wew I realize version 0.4.2 works normally. It's unclear what the problem is with higher versions

**Comment by Nika0000** [comment]
@QuangTom This problem has been fixed in the new [version](https://pub.dev/packages/cloudflare_turnstile/versions/1.2.4).

**Comment by QuangTom** [comment]
Thank for your help :D
