### ISSUE TITLE
Turnstile is appearing twice after flutter update.

### ISSUE THREAD

**Issue by karmicdice** [Nika0000/cloudflare_turnstile#4]
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (9 days ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3

Running on Android Studio.

I have double checked, the code is added only once.

![Screenshot 2024-07-25 at 23 31 58](https://github.com/user-attachments/assets/6ccd2593-ee08-4f97-b9d1-e78ac9cde051)

**Comment by karmicdice** [comment]
Only the one on top is clickable.


https://github.com/user-attachments/assets/82cdec86-dae6-4d61-b852-2e384cef75a0

**Comment by Nika0000** [comment]
@karmicdice Try the new [version](https://pub.dev/packages/cloudflare_turnstile/versions/1.2.6). Also, I will leave this issue open, if there is any problem, write it here, I haven't tested it on the new version, unfortunately.

**Comment by karmicdice** [comment]
Thanks. It appears adding `.hasChildNodes()` check has fixed it. I ran through on Android and iOS emulators. So far so good.
