### ISSUE TITLE
With version 2.x CloudFlareTurnstile widget is not initiated

### ISSUE THREAD

**Issue by hintbox** [Nika0000/cloudflare_turnstile#7]
Hi, everything works fine with v1.2.6 but when upgrading to 2.0.1 the widget is not loaded and token is not triggered. What is the problem. 

 `
CloudFlareTurnstile(
  siteKey: Build.CAPTCHA_SITE_KEY,
  baseUrl: Build.CAPTCHA_SITE_DOMAIN,
  mode: TurnstileMode.invisible,
  action: "lock",
  controller: turnstileController,
  onTokenExpired: () {
    debugPrint("cloudflare-onTokenExpired-----");
  },
  onTokenRecived: (token) async {
    if (await turnstileController.isExpired()) {
      debugPrint("cloudflare-token-token is expired. retry new token");
      debugPrint("cloudflare-token-expired-----");
      debugPrint(token);
      debugPrint("cloudflare-token-expired-----");
      turnstileController.refreshToken();

      return;
    }

    debugPrint("cloudflare-token-----");
    debugPrint(token);
    debugPrint("cloudflare-token-----");
  },
  options: TurnstileOptions(
    retryAutomatically: true,
    refreshTimeout: TurnstileRefreshTimeout.auto,
    refreshExpired: TurnstileRefreshExpired.auto,
  ),
),
`

**Comment by Nika0000** [comment]
@hintbox hi, thanks for reporting the issue.

Just to help me narrow down the problem, could you confirm a few details:

1. Are you running the app on iOS, and if so, is it on a real device or simulator?
2. Does the widget fail to load only in version `2.0.1`, or does the issue persist event after downgrading back to `1.2.6`?
3. Are there any errors or logs printed in the console when the widget fails to load?

Additionally, since you are using the `invisible` widget mode, I would recommend inplementing the `onError` function in the `turnstileController` to capture more detailed error messages. This might give better insights into what`s causing the widget not to load. 

Here`s an example:
```dart
turnstileController.onError((error) => print("Turnstile error: ${error.message}"));
```

Let me know if this helps or if you still encounter the problem after trying the above!

**Comment by hintbox** [comment]
Hi, thank you for your quick response. 
1. yes ios and it is simulator
2. version 1.2.6 works fine both real device or simulator. problem is with 2.0.1
3. i also added onError but does not received and error message

Also at cloudflare panel, the widget mode is defined invisible, which i use keys in the app

**Comment by Nika0000** [comment]
> Hi, thank you for your quick response.
> 
> 1. yes ios and it is simulator
> 2. version 1.2.6 works fine both real device or simulator. problem is with 2.0.1
> 3. i also added onError but does not received any error message
> 
> Also at cloudflare panel, the widget mode is defined invisible, which i use keys in the app

While I know there are some breaking changes in version `2.0.1`, it doesn’t sound like those are causing this particular issue. The problem might be related to how the widget is being rendered in your app.

Even though you're using `invisible` mode, the widget still needs to be part of the Flutter widget tree to function properly. 

**Ensure the widget is in the widget tree** - Even if it’s invisible, it still needs to be in the Flutter build method.

Also, I just released a [new version](https://pub.dev/packages/cloudflare_turnstile) with a few things fixed, so it might be worth upgrading to see if that resolves your issue.

**Comment by hintbox** [comment]
Hi, i upgraded new version but still problem continues. Widget is in the widget tree, i added image.
![Screenshot 2024-09-30 at 09 54 13](https://github.com/user-attachments/assets/97e366cd-8eae-4a2d-a7d9-a0ee12351e3b)

**Comment by hintbox** [comment]
I upgraded web package to 1.1.0 and received log
`[cloudflare_turnstile] Error: 300030.`

**Comment by Nika0000** [comment]
It seems like the error popped up while building the `webview_flutter_wkwebview` package, which is a dependency of the cloudflare_turnstile package you're using. It's possible that the issue lies with mismatched versions or build cache issues.
- Clear the Flutter build cache (if you haven`t tried this yet)

I'll try to resolve this issue as quickly as I can.

**Comment by hintbox** [comment]
hi, i have overrided webview_flutter_wkwebview version to 3.15.0 and cleaned build cache but same problem goes on. also tried on both real device and simulator.

**Comment by hintbox** [comment]
hi @Nika0000, do you have a solution for new version?

**Comment by Nika0000** [comment]
> hi @Nika0000, do you have a solution for new version?

Hi, i'm still working on it and trying my best to fix things. Just to confirm, does this issue only shown up with the `invisible` widget mode? Have you tried using test key yet? It might also help to try using the `managed` widget mode with the test key to see if the problem persists there.

```
// Visible Test SiteKey
1x00000000000000000000AA

// Invisible Test SiteKey
1x00000000000000000000BB
```

And finally :) please try the example. I`ve tried many things that could have caused this problem, but everything seems to be working fine.

https://github.com/user-attachments/assets/27de4226-64b0-4a4a-9c75-f9dd4f349eb6

**Comment by doodev** [comment]
Hi @Nika0000 

Thanks for your efforts for this library.

I have encountered same error. Error shows up whether it is managed or invisible mode. (Latest version 2.0.3)

> Turnstile error: An unspecified error occurred in the visitor while they were solving a challenge.

I have tried both on android emulator and real device. 

This error does not occur in debug mode. Everything works fine in debug mode. Only and always occurs in release mode on both emulator and android devices.

Below is the error printed in console in release ( managed mode):
```
E/flutter (19583): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Unable to find a PlatformView or View instance: 1, null
E/flutter (19583):      at io.flutter.plugins.webviewflutter.m.a(Unknown Source:60)
E/flutter (19583):      at io.flutter.plugin.platform.x.M(Unknown Source:39)
E/flutter (19583):      at io.flutter.plugin.platform.x$a.f(Unknown Source:38)
E/flutter (19583):      at l0.m$a.d(Unknown Source:263)
E/flutter (19583):      at l0.m$a.a(Unknown Source:175)
E/flutter (19583):      at m0.i$a.a(Unknown Source:17)
E/flutter (19583):      at b0.c.i(Unknown Source:18)
E/flutter (19583):      at b0.c.j(Unknown Source:41)
E/flutter (19583):      at b0.c.f(Unknown Source:0)
E/flutter (19583):      at b0.b.run(Unknown Source:12)
E/flutter (19583):      at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (19583):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (19583):      at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (19583):      at android.os.Looper.loop(Looper.java:288)
E/flutter (19583):      at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (19583):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (19583):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (19583):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (19583): , null, null)
E/flutter (19583): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
E/flutter (19583): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
E/flutter (19583): <asynchronous suspension>
E/flutter (19583): #2      SurfaceAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1040)
E/flutter (19583): <asynchronous suspension>
E/flutter (19583): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:827)
E/flutter (19583): <asynchronous suspension>
I/flutter (19583): Turnstile error: An unspecified error occurred in the visitor while they were solving a challenge.
```

It seems that flutter webview have some issues. I have encountered problems with loading and running custom javascript with flutter webview controller in the past. I have used [https://pub.dev/packages/flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) successfully. This library has normal webview like flutter webview; and also have headless webview to be used without rendering webview widget. I have used headless webview [https://inappwebview.dev/docs/webview/headless-in-app-webview](https://inappwebview.dev/docs/webview/headless-in-app-webview) for calling javascript functions without widget.  

I also had crashes on android emulator like the other issue you mentioned. It seems there is a problem with current webview.

If you can replace flutter webview with this library, these errors may be solved.

I will also look into your code and try with that library when I have time.

**Comment by Nika0000** [comment]
Thanks @doodev . You're right. I'll switch back to using `flutter_inappwebview`

**Comment by hintbox** [comment]
hi @Nika0000 what will be next update release time? Thank you.

**Comment by Nika0000** [comment]
> hi @Nika0000 what will be next update release time? Thank you.

Approximately 2-3 days, with a target date around October 15th.

**Comment by Koleshy** [comment]
Hello @Nika0000 , thanks for your efforts!

Please, if possible, in the new version, consider exposing a builder or a state variable for when the page is loading (loading progress), so I can display my custom loading widget while the captcha website is being displayed.

Best regards.

**Comment by hintbox** [comment]
hi, @Nika0000  any update

**Comment by Nika0000** [comment]
Before the new version is released, try adding this to your pubspec.yaml:
```YML
  cloudflare_turnstile:
    git:
      url: https://github.com/Nika0000/cloudflare_turnstile.git
      ref: legacy
```
Invisible widget works differently now. Check out the [README.md](https://github.com/Nika0000/cloudflare_turnstile/tree/legacy?tab=readme-ov-file#using-turnstile-invisible-mode) for the details. Also the invisible widget mode isn't available yet on the web platform.

**Comment by hintbox** [comment]
Hi, i received this error within a loop. 
`TurnstileException -1: The operation couldn’t be completed. (NSURLErrorDomain error -999.)`

**Comment by hintbox** [comment]
hi @Nika0000 , as a service it works well. Thank you 🙏

**Comment by hintbox** [comment]
@Nika0000 how can we receive token from invisible when refresh called. currently i think, we should call `  turnstile.getToken();` for each time?

**Comment by hintbox** [comment]
is it possible to pass "onTokenReceived", "onTokenExpired" and "onError" functions for invisible item. 
i just logged this
`[JavaScript Handler "TokenExpired"] Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _TurnstileInvisible._createChannels.<anonymous closure> (package:cloudflare_turnstile/src/widget/impl/turnstile_widget.dart:619:23)
#2      IOSInAppWebViewController._handleMethod (package:flutter_inappwebview_ios/src/in_app_webview/in_app_webview_controller.dart:1538:73)
#3      InternalChannelController.initMethodCallHandler.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:631:30)
#4      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#5      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:618:35)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:347:15)
#8      _rootRun (dart:async/zone.dart:1399:13)
#9      _CustomZone.run (dart:async/zone.dart:1301:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#11     _invoke2 (dart:ui/hooks.dart:346:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)`

**Comment by Nika0000** [comment]
> is it possible to pass "onTokenReceived", "onTokenExpired" and "onError" functions for invisible item. 
> i just logged this
> `[JavaScript Handler "TokenExpired"] Bad state: Future already completed
> #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
> #1      _TurnstileInvisible._createChannels.<anonymous closure> (package:cloudflare_turnstile/src/widget/impl/turnstile_widget.dart:619:23)
> #2      IOSInAppWebViewController._handleMethod (package:flutter_inappwebview_ios/src/in_app_webview/in_app_webview_controller.dart:1538:73)
> #3      InternalChannelController.initMethodCallHandler.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:631:30)
> #4      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
> #5      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
> #6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:618:35)
> #7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:347:15)
> #8      _rootRun (dart:async/zone.dart:1399:13)
> #9      _CustomZone.run (dart:async/zone.dart:1301:19)
> #10     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
> #11     _invoke2 (dart:ui/hooks.dart:346:10)
> #12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
> #13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
> #14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
> #15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
> #16     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)`

No, `onTokenReceived`, `onTokenExpired`, and `onError` are part of the visible widget, not the invisible one. However, the invisible widget has all the same functions that work exactly as they do in the visible widget. I’ve noted the issue you mentioned, and I’ll fix it tomorrow. I’ll also add more examples on how to use it.

**Comment by hintbox** [comment]
thank you @Nika0000 🙏

**Comment by doodev** [comment]
Hi @Nika0000 

I have not been able look into your code, I have been busy and I've switched to google recaptcha v3 for now.

As the issue is closed, I just quickly tried this new version with inappwebview.

Both manual and invisible  works fine under debug and release mode now. 👍  (Tested with emulator and real device)
