### ISSUE TITLE
retry mechanism for invisible mode should be added

### ISSUE THREAD

**Issue by hintbox** [Nika0000/cloudflare_turnstile#9]
Hi, with new version sometimes i received this `TurnstileException: An unspecified error occurred in the visitor while they were solving a challenge.` error. is it possible to add onTokenreceived, onError etc. for handling error or expired token's detection. Thank you

**Comment by Nika0000** [comment]
Hi, `onTokenReceived` and `onTokenExpired` callbacks have already been added in the [new version](https://pub.dev/packages/cloudflare_turnstile).

Example:
```dart
await CloudflareTurnstile.invisible(
  siteKey: '1x00000000000000000000BB',
  onTokenReceived: (token) {
    print(token);
  },
  onTokenExpired: () {
    print('Token Expired');
  },
).getToken();
```
